[project]
name = "csm-rewards"
version = "0.1.0"
description = "CSM rewards"
readme = "README.md"
requires-python = ">=3.12,<4.0"
license = "MIT"
dependencies = [
    "eth-wake",
    "python-dotenv>=1.2.2,<2.0.0",
    "requests>=2.32.4,<3.0.0",
    "setuptools<84",
]

[tool.uv]
package = false

[tool.uv.sources]
eth-wake = { git = "https://github.com/Ackee-Blockchain/wake", tag = "v4.22.1" }
