---
name: Automated update

on:
  schedule:
    - cron: "0 */1 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  testnet:
    uses: ./.github/workflows/_update.yml
    with:
      branch: holesky
      distributor: "0xD7ba648C8F72669C6aE649648B516ec03D07c8ED"
    secrets: inherit
