---
name: Regular checks

on:
  schedule:
    - cron: "0 */1 * * *"
  workflow_dispatch:

jobs:
  testnet:
    uses: ./.github/workflows/_check.yml
    with:
      notify: true
      chain: holesky
      distributor: "0xD7ba648C8F72669C6aE649648B516ec03D07c8ED"
    secrets: inherit

  mainnet:
    uses: ./.github/workflows/_check.yml
    with:
      notify: true
      chain: mainnet
      distributor: "0xD99CC66fEC647E68294C6477B40fC7E0F6F618D0"
    secrets: inherit
