---
name: Regular checks

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  testnet:
    uses: ./.github/workflows/_check.yml
    with:
      notify: true
      chain: hoodi
      distributor: "0xaCd9820b0A2229a82dc1A0770307ce5522FF3582"
    secrets: inherit

  # mainnet:
  #   uses: ./.github/workflows/_check.yml
  #   with:
  #     notify: true
  #     chain: mainnet
  #     distributor: "0xD99CC66fEC647E68294C6477B40fC7E0F6F618D0"
  #   secrets: inherit
