---
name: Automated update

on:
  # schedule:
  #   - cron: "0 */3 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  # testnet:
  #   uses: ./.github/workflows/_update.yml
  #   with:
  #     chain: hoodi
  #     distributor: "0xaCd9820b0A2229a82dc1A0770307ce5522FF3582"
  #   secrets: inherit

  mainnet:
    uses: ./.github/workflows/_update.yml
    with:
      chain: mainnet
      distributor: "0xD99CC66fEC647E68294C6477B40fC7E0F6F618D0"
    secrets: inherit
